name: 'pnpm installation'
description: 'Install and audit dependencies for pnpm'
inputs:
  cache: # id of input
    description: 'The location of the pnpm cache'
    required: false
    default: '.pnpm-store'

runs:
  using: 'composite'
  steps:
    - run: echo '${{ toJSON(inputs) }}'
      shell: bash

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.15.1

    - name: setup pnpm config
      run: pnpm config set store-dir ${{ inputs.cache }}
      shell: bash

    - name: Set node version to 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'

    - name: install dependencies
      run: pnpm install
      shell: bash
