name: deploy-web

env:
  BASE_URL: /
  BUILD_PACKAGE_NAME: 'docs'
  PUBLISH_DIR: ./packages/docs/dist

# 手动触发，不需要自动部署
# 自动部署的时机是在publish之后
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest
    timeout-minutes: 10
    steps: # 任务的步骤
      - name: checkout code repository # 步骤的名字 切到对应的分支
        uses: actions/checkout@v2 # 使用actions/checkout@v2这个action
        with: # 这个action的参数
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: ./.github/actions/deploy-docs
        with:
          build: BASE_URL=${{ env.BASE_URL }} pnpm -r build --filter=${{ env.BUILD_PACKAGE_NAME }}
          publish_dir: ${{ env.PUBLISH_DIR }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
