name: deploy

env:
  BASE_URL: /vue3-dnd

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

jobs:
  npm:
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - name: build project
        run: BASE_URL=$BASE_URL pnpm -r build --filter=docs

      - name: Run Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./packages/docs/src/.vitepress/dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
