## Listens to the CI workflow and runs the publish command to main when applicable.

name: publish

concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

jobs:
  publish-npm:
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 10
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - name: Run Build
        run: pnpm -r build

      - name: Publish
        run: pnpm -r publish

